

#######################
#        BASE         #
#######################


FROM python:3.12 AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1 \
	POETRY_VERSION=1.7.1 \
	POETRY_CACHE_DIR=/tmp/poetry_cache \
	WORKDIR_PATH=/usr/src/app/backend

WORKDIR $WORKDIR_PATH

COPY . /usr/src/app/backend



#######################
#        BUILD        #
#######################


FROM base AS build

COPY pyproject.toml poetry.lock .

RUN --mount=type=cache,target=$POETRY_CACHE_DIR \
	pip install --no-cache-dir "poetry==$POETRY_VERSION" \
	&& poetry config virtualenvs.in-project true \
	&& pip install --upgrade pip \
	&& poetry install --no-root


#######################
#       RUNTIME       #
#######################


FROM base AS runtime

ENV PATH=/usr/src/.venv/bin:$PATH \
	POETRY_VIRTUAL_ENV=$WORKDIR_PATH/.venv \
	VIRTUAL_ENV=/usr/src/.venv \
	PYTHONPATH=/usr/src/.venv/bin

COPY --from=build $POETRY_VIRTUAL_ENV $VIRTUAL_ENV

# NOTE: Switch from root in production!
